# Generated by Django 4.1 on 2023-02-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='Material Name')),
                ('material_type', models.CharField(max_length=100, verbose_name='Type of Material')),
                ('melting_point', models.FloatField(null=True, verbose_name='Melting Point')),
                ('thermal_conductivity', models.FloatField(null=True, verbose_name='Thermal Conductivity')),
                ('density', models.FloatField(null=True, verbose_name='Density')),
                ('specific_heat', models.FloatField(null=True, verbose_name='Specific Heat')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.IntegerField(unique=True, verbose_name='Property Number')),
                ('property_name', models.CharField(max_length=200, verbose_name='Property Name')),
                ('property_unit_si', models.CharField(max_length=100, verbose_name='SI unit')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_no', models.IntegerField(verbose_name='Property Number')),
                ('minimum_value', models.FloatField(verbose_name='Minimum User Input Value')),
                ('maximum_value', models.FloatField(verbose_name='Maximum User Input Value')),
                ('search_date', models.DateTimeField(verbose_name='Time of Query')),
                ('property_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_search.propertieslist')),
            ],
        ),
    ]
